name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

env:
  IMAGE_NAME: rajcloud12/python-project  # Replace with your DockerHub repository name
  IMAGE_TAG: latest  # Tag for the Docker image

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}  
          password: ${{ secrets.DOCKER_PASS }}  

      # Step 3: Build the Docker Image
      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      # Step 4: Push Docker Image to DockerHub
      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG
