name: Docker Build and Push

on:
    push:
        branches:
            - main

env:
    IMAGE_NAME: rajcloud12/python
    IMAGE_TAG: latest

jobs:
    build:
        name: Build Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
                uses: actions/checkout@v3

            - name: Log in to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_USER }}
                    password: ${{ secrets.DOCKER_PASS }}

            - name: Check for Dockerfile
                run: |
                    if [ ! -f Dockerfile ]; then
                        echo "Error: Dockerfile not found in the build context!"
                        exit 1
                    fi

            - name: Build Docker Image
                run: |
                    docker build -t $IMAGE_NAME:$IMAGE_TAG .
                    docker images | grep "$IMAGE_NAME" || (echo "Image not found locally after build!" && exit 1)

    push:
        name: Push Docker Image
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Log in to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_USER }}
                    password: ${{ secrets.DOCKER_PASS }}

            - name: Push Docker Image
                run: |
                    docker push $IMAGE_NAME:$IMAGE_TAG || (echo "Error during Docker push!" && exit 1)
                    echo "Image successfully pushed to Docker Hub!"
