name: Basic Workflow

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "Hello, GitHub Actions!"
