name: Docker Build and Push

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

env:
  IMAGE_NAME: rajcloud12/python-project
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Docker Login
      - name: Docker Login
        run: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      # Step 4: Push Docker Image to DockerHub
      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG
